import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import MobileNav from "@/components/MobileNav";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="relative">
      <Navbar />
      <MobileNav />

      <div className="flex">
        <Sidebar />

        <section className="flex flex-1 h-screen flex-col px-6 pb-6 pt-28 max-md:pb-14 sm:px-14 bg-slate-50">
          <body className={`w-full ${poppins.className}`}>{children}</body>
        </section>
      </div>
    </main>
  );
}
